export const ROLES = {
  SUPERADMIN: "SuperAdmin",
  ADMIN: "Admin",
  DEPARTMENT_MANAGER: "DepartmentManager",
  STUDENT: "Student",
};

export const PERMISSIONS = {
  MANAGE_STUDENTS: "manage_students",
  MARK_ATTENDANCE: "mark_attendance",
  VIEW_REPORTS: "view_reports",
  MANAGE_ADMINS: "manage_admins",
  MANAGE_DEPARTMENT_MANAGERS: "manage_department_managers",
  SYSTEM_SETTINGS: "system_settings",
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPERADMIN]: [
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_ADMINS,
    PERMISSIONS.MANAGE_DEPARTMENT_MANAGERS,
    PERMISSIONS.SYSTEM_SETTINGS,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.DEPARTMENT_MANAGER]: [
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.STUDENT]: [PERMISSIONS.VIEW_REPORTS],
};